//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dining_Meal_Plan_Change_History
    {
        public int ID_NUM { get; set; }
        public string OLD_PLAN { get; set; }
        public string OLD_PLAN_ID { get; set; }
        public string NEW_PLAN { get; set; }
        public string NEW_PLAN_ID { get; set; }
        public string SESS_CDE { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE { get; set; }
    }
}
