//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordon360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dining_Mealplan_Form_Submissions
    {
        public int formID { get; set; }
        public string ID_NUM { get; set; }
        public string Student_Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Address { get; set; }
        public string Residence_Hall { get; set; }
        public string MP_Code { get; set; }
        public string MealPlan { get; set; }
        public Nullable<System.DateTime> MaxReceivedDate { get; set; }
    }
}
